version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: assignment
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=admin
    command: ["redis-server", "--requirepass", "exampleRedisPass"]
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge
